blank_issues_enabled: true
contact_links:
  - name: LLSM_Processing_GUI Wiki
    url: https://github.com/abcucberkeley/LLSM_Processing_GUI/wiki
    about: We have an extensive wiki that can answer most questions about the GUI's usage
